build:
    environment:
        php:
            version: '7.2'
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    - phpcs-run
                    - vendor/bin/security-checker security:check

        coverage:
            tests:
                override:
                    - command: vendor/bin/phpunit
                      coverage:
                        file: docs/coverage.xml
                        format: clover

checks:
    php: true

filter:
    excluded_paths:
        - tests/*
